import type { Metadata } from 'next'
import SeoTemplatePage from '@/components/SeoTemplatePage'

const siteUrl = (
  process.env.NEXT_PUBLIC_SITE_URL ?? 'https://snapbrand-snowy.vercel.app'
).replace(/\/$/, '')

export const metadata: Metadata = {
  title: 'Brand Guide Template | Create Your Brand Standards',
  description:
    'Professional brand guide template for startups and small businesses. Document colors, fonts, logo rules, and brand voice.',
  openGraph: {
    title: 'Brand Guide Template | Create Your Brand Standards',
    description:
      'Professional brand guide template for startups and small businesses. Document colors, fonts, logo rules, and brand voice.',
    url: `${siteUrl}/brand-guide-template`,
    siteName: 'SnapBrand',
    type: 'website',
  },
  alternates: {
    canonical: `${siteUrl}/brand-guide-template`,
  },
}

export default function BrandGuideTemplatePage() {
  const sections = [
    {
      title: 'What Is a Brand Guide?',
      content: `A brand guide (also called a brand standard or brand manual) is a living document that defines how your brand looks and communicates. Unlike static templates, a brand guide evolves with your business — it's the source of truth for anyone representing your brand.`,
    },
    {
      title: 'The Difference Between Brand Guide and Brand Guidelines',
      content:
        'Often used interchangeably, "brand guide" and "brand guidelines" refer to the same thing. Both are comprehensive documents that specify how to use your brand elements. The term you use doesn\'t matter — what matters is having the documentation.',
    },
    {
      title: 'Key Elements Your Brand Guide Should Cover',
      content: [
        'Logo Specifications: File formats, usage rules, spacing, and variations',
        'Color System: Pantone, CMYK, RGB, and hex codes for all brand colors',
        'Typography: Font selections, sizes, weights, and line-height specifications',
        'Imagery & Photography: Style guidelines for photos and graphics',
        'Voice & Messaging: Tone guidelines and key messages',
        'Application Examples: Real-world examples of correct brand usage',
        'What Not To Do: Common mistakes and misuses to avoid',
      ],
    },
    {
      title: 'Who Uses Brand Guides?',
      content: [
        'Internal Teams: Designers, marketers, and content creators',
        'External Partners: Freelancers, agencies, and contractors',
        'Franchisees: For multi-location businesses ensuring consistency',
        'Vendors: Printers, manufacturers, and partners',
        'New Employees: For onboarding and training',
      ],
    },
    {
      title: 'Benefits of Having a Brand Guide',
      content:
        'A documented brand guide prevents brand dilution, accelerates team onboarding, improves customer recognition, and establishes credibility. It's the difference between a brand that looks professional and organized versus one that appears inconsistent and amateur.',
    },
    {
      title: 'Build Your Brand Guide With SnapBrand',
      content:
        'Start with a complete brand system generated by AI in 60 seconds. Your brand guide should be based on a cohesive visual identity, and SnapBrand gives you exactly that — colors that work together, fonts that complement each other, and messaging that aligns with your vision.',
    },
  ]

  const relatedPages = [
    { href: '/brand-guidelines-template', label: 'Brand Guidelines Template' },
    { href: '/brand-guide-examples', label: 'Brand Guide Examples' },
    { href: '/brand-identity-template', label: 'Brand Identity Template' },
  ]

  return (
    <SeoTemplatePage
      keyword="brand guide template"
      title="Brand Guide Template | Create Your Brand Standards"
      metaDescription="Professional brand guide template for startups and small businesses. Document colors, fonts, logo rules, and brand voice."
      h1="Brand Guide Template"
      intro="Create a professional brand guide that ensures consistency across all your marketing materials. This template helps you document your logo, colors, typography, and brand voice."
      sections={sections}
      relatedPages={relatedPages}
    />
  )
}
